version: "3.9"  # optional since v1.27.0
services:
  web:
    image: orderich-dev:latest
    build: .
    restart: always
    command: gunicorn --bind :80 --preload --workers 4 --worker-class uvicorn.workers.UvicornWorker saleor.asgi:application
    # args:
    #  ENV: ${ENV} # from .env file
    env_file:
      - deploy.env
    ports:
      - "8000:80"
  worker:
    image: orderich-dev:latest
    build: .
    restart: always
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -E
    #args:
    #  ENV: ${ENV} # from .env file
    env_file:
      - deploy.env


